
 export const data = [
  {
    id: 1,
    name: "Paneer Tikka",
    category: "main course",
    image: "/paneertikka.jpg",
    price: "120",
  },
  {
    id: 2,
    name: "Veg Biryani",
    category: "main course",
    image: "/veg-biryani.jpg",
    price: "150",
  },
  {
    id: 3,
    name: "Palak Paneer",
    category: "main course",
    image: "/paneer-palak.jpg",
    price: "140",
  },
  {
    id: 4,
    name: "Pav Bhaji",
    category: "spicy",
    image: "/pavbhaji.jpg",
    price: "80",
  },
  {
    id: 5,
    name: "Chole Bhature",
    category: "spicy",
    image: "/chole-bhature.jpg",
    price: "90",
  },
  {
    id: 6,
    name: "Strawberry Shake",
    category: "beverage",
    image: "/strawberry.jpg",
    price: "70",
  },
  {
    id: 7,
    name: "Samosa",
    category: "spicy",
    image: "/samosa.jpg",
    price: "20",
  },
  {
    id: 8,
    name: "Lassi",
    category: "beverage",
    image: "/lassi.jpg",
    price: "30",
  },
  {
    id: 9,
    name: "Jalebi",
    category: "Sweet",
    image: "/jalebi.jpg",
    price: "40",
  },
  {
    id: 10,
    name: "Chocolate Shake",
    category: "beverage",
    image: "/chocolate.jpg",
    price: "75",
  },
  {
    id: 11,
    name: "Ladoo",
    category: "Sweet",
    image: "/Ladoo.jpg",
    price: "30",
  },
  {
    id: 12,
    name: "Oreo Shake",
    category: "beverage",
    image: "/oreo.jpg",
    price: "80",
  },
  {
    id: 13,
    name: "Orange Juice",
    category: "beverage",
    image: "/orange.jpg",
    price: "40",
  },
  {
    id: 14,
    name: "Mango Juice",
    category: "beverage",
    image: "/mango.jpg",
    price: "45",
  },
  {
    id: 15,
    name: "Apple Juice",
    category: "beverage",
    image: "/apple.jpg",
    price: "50",
  },
  {
    id: 16,
    name: "Lemon Juice",
    category: "beverage",
    image: "/lemon.jpg",
    price: "30",
  },
  {
    id: 17,
    name: "Gulab Jamun",
    category: "Sweet",
    image: "/gulab-jamun.jpg",
    price: "25",
  },
  {
    id: 18,
    name: "Gajar Halwa",
    category: "Sweet",
    image: "/halwa.jpg",
    price: "75",
  },
  {
    id: 19,
    name: "Kheer",
    category: "Sweet",
    image: "/kheer.jpg",
    price: "80",
  },
  {
    id: 20,
    name: "Kulfi",
    category: "Sweet",
    image: "/kulfi.jpg",
    price: "60",
  },
  {
    id: 21,
    name: "Ice Cream",
    category: "Sweet",
    image: "/ice-cream.jpg",
    price: "40",
  },
  {
    id: 22,
    name: "Cake",
    category: "Sweet",
    image: "/cake.jpg",
    price: "45",
  },
  {
    id: 23,
    name: "Rice Dal",
    category: "main course",
    image: "/rice-dal.jpg",
    price: "120",
  },
  {
    id: 24,
    name: "Rice Vege",
    category: "main course",
    image: "/rice-vege.jpg",
    price: "120",
  },
  {
    id: 25,
    name: "Pani-poori",
    category: "spicy",
    image: "/pani-poori.jpg",
    price: "20",
  },
];
